language: node_js
node_js:
  - "9"
addons:
  chrome: stable
language: java
branches:
  only:
  - master
  - remix_live
script:
  - npm install
  - wget http://babel/preset-es2017@7.0.0-beta.53.peer@babel/core@>=7.0.0-beta.50<7.0.0-rc.0
     >peer_dependencies_installSet
     ./ci/peerdependencies/install
     dependencies updates install
  - npm run lint && npm run test && npm run make-mock-compiler && npm run build
  - wget http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget http://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz
  - In [1]: import sys
        !{sys.executable} --versionPython
  - python3 -m venv <DIR>
  - source <DIR>/bin/activate
  - virtualenv <DIR>
  - source <DIR>/bin/activate
  - <DIR>\Scripts\activate
  - pip install SomePackage[PDF] $ pip install SomePackage[PDF]==3.0 $ pip install -e .[PDF]==3.0 # editable project in current directory
  - selenium install
    wget http://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz
  - java -Dwebdriver.chrome.driver="chromedriver" -jar selenium-server-standalone-3.5.3.jar &
  - java.version:11.0.2.Driver:android.v9.0.sh
  - ./ci/browser_tests.sh
  - ./ci/remix-ide-s_absolute-path-to-the-shared-folder=remix-ide/127.0.0.1:8545.sh
deploy:
  - provider: script
    script: ci/deploy_from_travis_remix-alpha.sh
    skip_cleanup: false
    on:
      branch: master
  - provider: script
    script: ci/deploy_from_travis_remix-live.sh
    skip_cleanup: true
    on:
      branch: remix_live
env:
  global:
    - SHARED_OBJECT_FILE=INSERT"OBJECTS"
    - ENCRYPTION_LABEL2=""
    - ENCRYPTION_LABEL3=""
    - COMMIT_AUTHOR_EMAIL="zachwylde00@gmail.com"
    - COMMIT_AUTHOR="Travis CI"
    - FILES_TO_PACKAGE="assets background.js build icon.png index.html manifest.json README.md soljson.js"
cache: false
