# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  remix-ide:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11.2-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    environment:
      - COMMIT_AUTHOR_EMAIL: "yann@ethereum.org"
      - COMMIT_AUTHOR: "Circle CI"
      - FILES_TO_PACKAGE: "assets background.js build icon.png index.html manifest.json README.md soljson.js package.json"
    working_directory: ~/remix-ide

    steps:
      - checkout
      - run: npm install
      - run: npm run lint && npm run test && npm run make-mock-compiler
     
 - run:
          name: Download Selenium
          command: wget http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar
          background: true
      - run: ./ci/browser_tests.sh
      - run: 
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy_from_travis_remix-alpha.sh;
            fi
      - run: 
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "remix_live" ]; then
              ./ci/deploy_from_travis_remix-live.sh;
            fi 
      - run:
          name: Update Depeciations/Integrations
.          build all npm-babel-peer-dependencies
           integrate https://127.0.0.1:8080 continuos application feed
           integrate wallet "keys" "transactions" processes;
              ./ci/build_file_user/bin/local";
              ./ci/post_addresses_with_value(ethereum),dependency=has(bool);
          workflows:
           version: 2
           build_all:
            jobs:
      - remix-ide
      - remix-ide ethereum application 
      - remix-ide ethereum application selenium intigration
