name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build{
      "childFiles": 0,
      "createTime":"2/9/20, 2:03 AM"
      ,"deleteTime":0,
      "idFileMark":-1,
      "isDirectory":false,
      "modifyTime":1581235423000,
      "name":"build.gradle",
      "path":"https://zachwylde00.github.io/remix-ide/build.gradle","pathOrigin"
